In [4]:
import math
import numpy as np
import pandas as pd

In [2]:
print(math.pi)

3.141592653589793


In [5]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr=np.array([1,2,'3'],dtype='float32')
arr[2]+3
arr.dtype

dtype('float32')

In [12]:
arr=np.array(['5','6','7','8'],dtype='int16')

In [13]:
arr.dtype

dtype('int16')

In [14]:
arr[0]

5

In [19]:
arr=arr.astype(np.float32)

In [20]:
arr.dtype

dtype('float32')

In [22]:
arr=np.array(['ayham','Ahmed','Islam'],dtype=np.unicode_)
print(f'dtype of array is {arr.dtype}')

dtype of array is <U5


In [23]:
arr=np.array([1,2,3,45])
print(arr)
type(arr)

[ 1  2  3 45]


numpy.ndarray

In [26]:
arr=np.array((1,2,3,4))
print(arr)
type(arr)

[1 2 3 4]


numpy.ndarray

In [27]:
arr=np.arange(0,12,2)

In [28]:
arr


array([ 0,  2,  4,  6,  8, 10])

In [29]:
arr.astype(np.float32)

array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float32)

In [37]:
arr,step_size=np.linspace(0,20,10,endpoint=False,retstep=True)

In [38]:
print(arr)
print(arr.size)
print('The step size is ' + str(step_size))

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
10
The step size is 2.0


In [44]:

arr=np.random.rand(3,3)
print(arr)

[[0.04145243 0.89471027 0.32028473]
 [0.1146585  0.84534136 0.55898039]
 [0.59464944 0.13606323 0.11286878]]


In [50]:
arr2 = np.array([[1,2], [3,4],[5,6]], dtype='i4')
zeros = np.zeros_like(arr2)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0 0]
 [0 0]
 [0 0]]
Data Type: int32


In [48]:
arr=np.empty((5,5))
print(arr)

[[6.23042070e-307 3.56043053e-307 1.60219306e-306 7.56571288e-307
  1.89146896e-307]
 [1.37961302e-306 1.05699242e-307 8.01097889e-307 1.78020169e-306
  7.56601165e-307]
 [1.02359984e-306 1.15710088e-306 6.23056330e-307 1.60219578e-306
  7.56601165e-307]
 [6.23061763e-307 9.34607074e-307 8.90098127e-307 8.90108313e-307
  6.23053954e-307]
 [1.86919513e-306 1.11261570e-306 1.42410974e-306 3.39986383e-317
  3.20558931e-317]]


In [60]:
arr=np.empty_like(arr)

In [61]:
arr

array([[[-1056214752,  1067792704,  1818408969],
        [ 1072472439, -2109806144,  1070890891]],

       [[ 1809146448,  1069374018,  1366206829],
        [ 1072368905,  -713195470,  1071768362]],

       [[ 1111400876,  1071843166,   602358316],
        [ 1069640325,  -557695016,  1069343991]]])

In [55]:
print(arr.shape)

(3, 2)


In [58]:
arr=np.array([ [[4,5,6],[8,9,9]] , [[8,10,12],[3,3,4]] ,[ [13,14,5],[15,6,8]]])

In [59]:
arr.shape

(3, 2, 3)

In [63]:
arr=np.array([ [3,5,6],[6,7,8] ])

In [64]:
arr.size

6

In [65]:
arr.shape

(2, 3)

In [66]:
np.random.rand(3)

array([0.99149848, 0.07858399, 0.96404695])

In [68]:
#np.random.seed(66)
np.random.rand(4)

array([0.19445006, 0.25121038, 0.75841639, 0.55761859])

In [84]:
arr=np.random.randint(10,20,10,'i4')
arr
arr=np.sort(arr)
arr

array([11, 12, 13, 14, 15, 16, 18, 18, 18, 19])

In [85]:
arr2=np.random.shuffle(arr)
print(arr2)

None


In [81]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [82]:
np.random.shuffle(arr)
print(arr)

[0 8 3 2 7 5 1 9 4 6]


In [86]:
arr=np.random.rand(5,5)
arr

array([[0.75254355, 0.86743047, 0.24041374, 0.49507776, 0.81924134],
       [0.82346043, 0.58259036, 0.22049671, 0.46511899, 0.2684468 ],
       [0.66264009, 0.60258084, 0.27634671, 0.33124961, 0.62496736],
       [0.41399645, 0.20195307, 0.59583513, 0.5272244 , 0.91850237],
       [0.03311538, 0.36905421, 0.4713992 , 0.26836313, 0.88105958]])

In [88]:
arr=np.array([1,2,3])
np.add(arr,[1,2,3],out=arr)
arr


array([2, 4, 6])

In [89]:
np.subtract(arr,[1,2,3],out=arr)

array([1, 2, 3])

In [94]:
arr1=np.random.rand(5,5)
arr1

array([[0.62620357, 0.89707165, 0.56546105, 0.69496209, 0.95649468],
       [0.29066945, 0.91653871, 0.61371532, 0.13837961, 0.06233661],
       [0.68056494, 0.01482088, 0.46059883, 0.02922097, 0.66343876],
       [0.47519173, 0.32918482, 0.7343371 , 0.06066645, 0.12548368],
       [0.55758925, 0.70146589, 0.02238126, 0.4294336 , 0.26228598]])

In [92]:
np.exp(arr1)

array([[1.71167536, 1.33993126, 1.05708269, 2.68810964, 2.64464716],
       [1.55916484, 2.50458768, 1.03901905, 1.46510617, 1.3018903 ],
       [2.24275276, 2.17205434, 2.10271634, 1.86736999, 1.271721  ],
       [2.39104508, 1.063788  , 1.05229294, 1.51498074, 2.59222367],
       [1.11213092, 2.71158509, 1.11362444, 2.43175856, 1.06237881]])

In [95]:
arr1

array([[0.62620357, 0.89707165, 0.56546105, 0.69496209, 0.95649468],
       [0.29066945, 0.91653871, 0.61371532, 0.13837961, 0.06233661],
       [0.68056494, 0.01482088, 0.46059883, 0.02922097, 0.66343876],
       [0.47519173, 0.32918482, 0.7343371 , 0.06066645, 0.12548368],
       [0.55758925, 0.70146589, 0.02238126, 0.4294336 , 0.26228598]])

In [96]:
arr1=np.sqrt(arr1)

In [97]:
arr1

array([[0.79133026, 0.94713866, 0.75197144, 0.83364386, 0.97800546],
       [0.53913769, 0.95736028, 0.78339985, 0.3719941 , 0.24967301],
       [0.8249636 , 0.12174104, 0.67867432, 0.17094143, 0.8145175 ],
       [0.68934152, 0.5737463 , 0.85693471, 0.24630559, 0.35423676],
       [0.74671899, 0.8375356 , 0.14960369, 0.65531183, 0.51213863]])

In [98]:
np.sum(arr1,axis=0)

array([3.59149206, 3.43752189, 3.22058402, 2.27819682, 2.90857137])

In [99]:
np.sum(arr1,axis=1)

array([4.30208968, 2.90156493, 2.61083789, 2.7205649 , 2.90130875])

In [101]:
arr1=np.sum(arr1,axis=1)

In [103]:
arr1.size

5

In [104]:
arr1

array([4.30208968, 2.90156493, 2.61083789, 2.7205649 , 2.90130875])

In [107]:
arr=np.array(range(100)).reshape(10,10)

In [108]:
print(arr[5,5])

55


In [109]:
print(arr[1:3,:])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [117]:
arr1=np.arange(16).reshape(4,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [129]:
print(arr1[[0,1,2]][:, [0,1,2]])  
print(arr1[[0,1,2]][:,[0,1,2]])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [131]:
print(arr1[[1,2,3],[1,2,3]])

[ 5 10 15]


In [132]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:
print(arr1[ [1,2,3] [:]][:,[1,2,3]])

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [143]:
arr=np.arange(25).reshape(5,5)
np.random.shuffle(arr)
arr

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [147]:
np.sort(arr,axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [149]:
arr.sort(axis=0)

In [150]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [153]:
newarr=np.array([[3,10,30],[50,80,60,],[8,9,10]])

In [154]:
newarr=np.sort(newarr)
newarr

array([[ 3, 10, 30],
       [50, 60, 80],
       [ 8,  9, 10]])

In [155]:
newarr=newarr.flatten()

In [156]:
newarr

array([ 3, 10, 30, 50, 60, 80,  8,  9, 10])

In [157]:
arr2=np.array([1,2,3,4])


In [158]:
arr3=arr2

In [159]:
arr3

array([1, 2, 3, 4])

In [160]:
arr2[0]=8

In [161]:
arr3

array([8, 2, 3, 4])

In [162]:
arr2

array([8, 2, 3, 4])

In [163]:
arr3=np.copy(arr2)

In [164]:
arr3

array([8, 2, 3, 4])

In [165]:
arr3[0]=10

In [166]:
arr3

array([10,  2,  3,  4])

In [167]:
arr2

array([8, 2, 3, 4])